<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:intf="http://www.jboss.com/jbosstm/xts/demo/Restaurant" xmlns:impl="http://www.jboss.com/jbosstm/xts/demo/Restaurant" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://www.jboss.com/jbosstm/xts/demo/Restaurant">

   <wsdl:message name="bookSeatsRequest">

      <wsdl:part name="how_many" type="xsd:int"/>

   </wsdl:message>

   <wsdl:message name="bookSeatsResponse">

   </wsdl:message>

   <wsdl:portType name="IRestaurantServiceAT">

      <wsdl:operation name="bookSeats" parameterOrder="how_many">

         <wsdl:input name="bookSeatsRequest" message="intf:bookSeatsRequest"/>

         <wsdl:output name="bookSeatsResponse" message="intf:bookSeatsResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="RestaurantServiceATSoapBinding" type="intf:IRestaurantServiceAT">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="bookSeats">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="bookSeatsRequest">

            <wsdlsoap:body use="literal" namespace="http://www.jboss.com/jbosstm/xts/demo/Restaurant"/>

         </wsdl:input>

         <wsdl:output name="bookSeatsResponse">

            <wsdlsoap:body use="literal" namespace="http://www.jboss.com/jbosstm/xts/demo/Restaurant"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="RestaurantServiceATService">

      <wsdl:port name="RestaurantServiceAT" binding="intf:RestaurantServiceATSoapBinding">

         <wsdlsoap:address location="http://localhost:8080/xts-demo-webservices/RestaurantServiceAT"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>