<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:intf="http://www.jboss.com/jbosstm/xts/demo/Taxi" xmlns:impl="http://www.jboss.com/jbosstm/xts/demo/Taxi" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://www.jboss.com/jbosstm/xts/demo/Taxi">

   <wsdl:message name="bookTaxiBARequest">

   </wsdl:message>

   <wsdl:message name="bookTaxiBAResponse">

      <wsdl:part name="bookTaxiBAResponse" type="xsd:boolean"/>

   </wsdl:message>

   <wsdl:portType name="ITaxiServiceBA">

      <wsdl:operation name="bookTaxi">

         <wsdl:input name="bookTaxiBARequest" message="intf:bookTaxiBARequest"/>

         <wsdl:output name="bookTaxiBAResponse" message="intf:bookTaxiBAResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="TaxiServiceBASoapBinding" type="intf:ITaxiServiceBA">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="bookTaxi">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="bookTaxiBARequest">

            <wsdlsoap:body use="literal" namespace="http://www.jboss.com/jbosstm/xts/demo/Taxi"/>

         </wsdl:input>

         <wsdl:output name="bookTaxiBAResponse">

            <wsdlsoap:body use="literal" namespace="http://www.jboss.com/jbosstm/xts/demo/Taxi"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="TaxiServiceBAService">

      <wsdl:port name="TaxiServiceBA" binding="intf:TaxiServiceBASoapBinding">

         <wsdlsoap:address location="http://localhost:8080/xts-demo-webservices/TaxiServiceBA"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>