package org.jboss.narayana.quickstarts.compensationsApi.hotel.jaxws;

import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.2-hudson-182-RC1 Generated source version: 2.0
 */
@WebServiceClient(name = "HotelServiceService", targetNamespace = "http://www.jboss.org/as/quickstarts/compensationsApi/travel/hotel")
public class HotelServiceService extends Service {

    private final static URL HOTELSERVICEBASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(HotelServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = HotelServiceService.class.getResource(".");
            url = new URL(baseUrl, "/WEB-INF/wsdl/HotelService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '/WEB-INF/wsdl/HotelService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HOTELSERVICEBASERVICE_WSDL_LOCATION = url;
    }

    public HotelServiceService(URL wsdlLocation, QName serviceName) {

        super(wsdlLocation, serviceName);
    }

    public HotelServiceService() {

        super(HOTELSERVICEBASERVICE_WSDL_LOCATION, new QName("http://www.jboss.org/jbosstm/xts/quickstarts/compensationsApi/travel",
                "HotelServiceService"));
    }

    @WebEndpoint(name = "HotelService")
    public HotelService getHotelService() {

        return super.getPort(new QName("http://www.jboss.org/jbosstm/xts/quickstarts/compensationsApi/travel", "HotelService"), HotelService.class);
    }

}