logging.level.org.apache.activemq.audit.base=ERROR
logging.level.org.apache.activemq.audit.message=ERROR
logging.level.org.apache.activemq.audit.resource=ERROR

# Artemis
spring.artemis.embedded.queues=foo,users,DLQ

# Database
spring.datasource.url=jdbc:h2:file:./target/camel-quickstart;DB_CLOSE_ON_EXIT=FALSE
spring.jpa.hibernate.ddl-auto=update

# TX manager
narayana.log-dir=./target/tx-object-store
narayana.recoveryDbUser=
narayana.recoveryDbPass=
narayana.messaginghub.enabled=true

# Enable shutdown endpoint
management.endpoint.shutdown.enabled=true
management.endpoints.web.exposure.include=health,shutdown
