package com.jboss.jbosstm.xts.demo.taxi;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-hudson-182-RC1
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ITaxiServiceBA", targetNamespace = "http://www.jboss.com/jbosstm/xts/demo/Taxi")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ITaxiServiceBA {


    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "bookTaxiBAResponse", partName = "bookTaxiBAResponse")
    public boolean bookTaxi();

}