logging.level.org.apache.activemq.audit.base=ERROR
logging.level.org.apache.activemq.audit.message=ERROR
logging.level.org.apache.activemq.audit.resource=ERROR

# Create updates queue.
spring.artemis.embedded.queues=updates

spring.jpa.hibernate.ddl-auto=update

# TX manager
narayana.log-dir=./target/tx-object-store
narayana.recoveryDbUser=
narayana.recoveryDbPass=
narayana.messaginghub.enabled=true
