#include <CosTransactions.idl>

/*
    The module scoping has been created to reflect the packages used within the Java source code of the Arjuna
    Transactions product trailmap.
 */
module com {
    module arjuna {
        module demo {
            module simple{
                /*
                    The Hello interface is derived from the CosTransactions::TransactionalObject. All the methods of an interface
                    derived from here automatically gain implicit transaction propogation characteristics
                 */
                interface Hello: CosTransactions::TransactionalObject
                {
                    /*
                        This will print hello to the screen under transactional control.
                        Clearly it is not a great example of what can be done transactionally (writing to the console
                        cannot be rolled back!).
                        However it suffices to illustrate that the product is correctly installed and configured.
                     */
                    void print_hello();
                };
            };
        };
    };
};