package org.jboss.narayana.quickstarts.compensationsApi.taxi1.jaxws;


import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.2-hudson-182-RC1 Generated source version: 2.0
 */
@WebServiceClient(name = "Taxi1ServiceService", targetNamespace = "http://www.jboss.org/as/quickstarts/compensationsApi/travel/taxi1")
public class Taxi1ServiceService extends Service {

    private final static URL TAXI1SERVICEBASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(Taxi1ServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = Taxi1ServiceService.class.getResource(".");
            url = new URL(baseUrl, "/WEB-INF/wsdl/Taxi1Service.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '/WEB-INF/wsdl/Taxi1Service.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TAXI1SERVICEBASERVICE_WSDL_LOCATION = url;
    }

    public Taxi1ServiceService(URL wsdlLocation, QName serviceName) {

        super(wsdlLocation, serviceName);
    }

    public Taxi1ServiceService() {

        super(TAXI1SERVICEBASERVICE_WSDL_LOCATION, new QName("http://www.jboss.org/jbosstm/xts/quickstarts/compensationsApi/travel",
                "Taxi1ServiceService"));
    }

    @WebEndpoint(name = "Taxi1Service")
    public Taxi1Service getTaxi1Service() {

        return super.getPort(new QName("http://www.jboss.org/jbosstm/xts/quickstarts/compensationsApi/travel", "Taxi1Service"), Taxi1Service.class);
    }

}