package org.jboss.narayana.quickstarts.compensationsApi.taxi2.jaxws;


import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.2-hudson-182-RC1 Generated source version: 2.0
 */
@WebServiceClient(name = "Taxi2ServiceService", targetNamespace = "http://www.jboss.org/as/quickstarts/compensationsApi/travel/taxi2")
public class Taxi2ServiceService extends Service {

    private final static URL Taxi2SERVICEBASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(Taxi2ServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = Taxi2ServiceService.class.getResource(".");
            url = new URL(baseUrl, "/WEB-INF/wsdl/Taxi2Service.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '/WEB-INF/wsdl/Taxi2Service.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        Taxi2SERVICEBASERVICE_WSDL_LOCATION = url;
    }

    public Taxi2ServiceService(URL wsdlLocation, QName serviceName) {

        super(wsdlLocation, serviceName);
    }

    public Taxi2ServiceService() {

        super(Taxi2SERVICEBASERVICE_WSDL_LOCATION, new QName("http://www.jboss.org/jbosstm/xts/quickstarts/compensationsApi/travel",
                "Taxi2ServiceService"));
    }

    @WebEndpoint(name = "Taxi2Service")
    public Taxi2Service getTaxi2Service() {

        return super.getPort(new QName("http://www.jboss.org/jbosstm/xts/quickstarts/compensationsApi/travel", "Taxi2Service"), Taxi2Service.class);
    }

}