name: QUICKSTART 17

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  quickstart-17:
    name: QUICKSTART test with JDK ${{ matrix.java-version }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        java-version: [ 17 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        name: Set up JDK ${{ matrix.java-version }}
        with:
          java-version: ${{ matrix.java-version }}

      - name: CORE test
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          WORKSPACE=$PWD ./scripts/hudson/quickstart.sh

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: artifacts
          path: |
            **/target/*surefire-reports*/
            **/*.log*
          if-no-files-found: error

