<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:intf="http://www.jboss.com/jbosstm/xts/demo/Restaurant" xmlns:impl="http://www.jboss.com/jbosstm/xts/demo/Restaurant" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://www.jboss.com/jbosstm/xts/demo/Restaurant">

   <wsdl:message name="bookSeatsBARequest">

      <wsdl:part name="in0" type="xsd:int"/>

   </wsdl:message>

   <wsdl:message name="bookSeatsBAResponse">

      <wsdl:part name="bookSeatsBAResponse" type="xsd:boolean"/>

   </wsdl:message>

   <wsdl:portType name="IRestaurantServiceBA">

      <wsdl:operation name="bookSeats" parameterOrder="in0">

         <wsdl:input name="bookSeatsBARequest" message="intf:bookSeatsBARequest"/>

         <wsdl:output name="bookSeatsBAResponse" message="intf:bookSeatsBAResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="RestaurantServiceBASoapBinding" type="intf:IRestaurantServiceBA">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="bookSeats">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="bookSeatsBARequest">

            <wsdlsoap:body use="literal" namespace="http://www.jboss.com/jbosstm/xts/demo/Restaurant"/>

         </wsdl:input>

         <wsdl:output name="bookSeatsBAResponse">

            <wsdlsoap:body use="literal" namespace="http://www.jboss.com/jbosstm/xts/demo/Restaurant"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="IRestaurantServiceBAService">

      <wsdl:port name="RestaurantServiceBA" binding="intf:RestaurantServiceBASoapBinding">

         <wsdlsoap:address location="http://localhost:8080/xts-demo-webservices/RestaurantServiceBA"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>